import Sidebar from '@components/Sidebar/Sidebar'
import Playlist from '@components/Playlist/Playlist'
import Player from '@components/Player/Player'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { getSession } from 'next-auth/react'
import { currentViewState } from '../atoms/viewAtom'
import { useRecoilValue } from 'recoil'
import Search from '@components/Search/Search'

const Home: NextPage = () => {
  const currentComponent = useRecoilValue(currentViewState)
  
  return (
    <div className={styles.home}>
      <Head>
        <title>Spotify 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sidebar />
        {currentComponent == 'playlist' && <Playlist />}
        {currentComponent == 'search' && <Search />}
      </main>

      <div className={styles.playerWrapper}>
        <Player />
      </div>
    </div>
  )
}

export default Home

// Server side render the user's session so we have the accessToken before it hits the client,
// required to fix issue on not having user's accessToken on initial render
export const getServerSideProps: GetServerSideProps = async(context) => {
  const session = await getSession(context)
  return {
    props: {
      session
    },
  }
}