import Sidebar from '@components/Sidebar/Sidebar'
import Content from '@components/Content/Content'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { getSession } from 'next-auth/react'

const Home: NextPage = () => {
  
  return (
    <div className={styles.home}>
      <Head>
        <title>Spotify 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sidebar />
        <Content />
      </main>

      <div>
        {/* Player */}
      </div>
    </div>
  )
}

export default Home

// Server side render the user's session so we have the accessToken before it hits the client,
// required to fix issue on not having user's accessToken on initial render
export const getServerSideProps: GetServerSideProps = async(context) => {
  const session = await getSession(context)
  return {
    props: {
      session
    },
  }
}