import Sidebar from '@components/Sidebar/Sidebar'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Spotify 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {/* Sidebar */}
        <Sidebar />
        {/* Content */}
      </main>

      <div>
        {/* Player */}
      </div>
    </div>
  )
}

export default Home
